trigger:
  branches:
    include:
    - operativef-dev

stages:
  - stage: build_linux_gpp
    dependsOn: []
    displayName: G++ Linux Build
    jobs:
    - job: build
      pool:
        vmImage: 'ubuntu-16.04'
        
      strategy:
        matrix:
          gpp_7:
            g++_version: '-7'
          gpp_8:
            g++_version: '-8'
          gpp_9:
            g++_version: '-9'

      steps:
      - script: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo add-apt-repository ppa:george-edison55/precise-backports
          sudo apt-get update
          sudo apt-get install g++$(g++_version) cmake
      - script: |
          mkdir build
          cd build
          cmake .. -DCMAKE_CXX_COMPILER=g++$(g++_version) -DMAKE_INCLUDE_TESTS=ON
          make VERBOSE=1
      - upload: build/boost_tmp_test
        artifact: tmp_test_gpp$(g++_version)

  - stage: test_linux_gpp
    displayName: G++ Linux Test
    dependsOn: build_linux_gpp
    jobs:
    - job: test
      pool:
          vmImage: 'ubuntu-16.04'
      strategy:
        matrix:
          gpp_5:
            g++_version: '-7'
          gpp_6:
            g++_version: '-8'
          gpp_7:
            g++_version: '-9'
      steps:
      - download: 'current'
        artifact: tmp_test_gpp$(g++_version)
      - script: |
          cd $(Pipeline.Workspace)/tmp_test_gpp$(g++_version)
          sudo chmod +x ./boost_tmp_test

  - stage: build_linux_clang
    dependsOn: []
    displayName: Clang Linux Build
    jobs:
    - job: build
      pool:
        vmImage: 'ubuntu-16.04'

      strategy:
        matrix:
          clang_5.0:
            clang_version: '-5.0'
          clang_6.0:
            clang_version: '-6.0'

      steps:
      - script: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo add-apt-repository ppa:george-edison55/precise-backports
          sudo add-apt-repository "deb http://llvm.org/apt/precise/ llvm-toolchain-precise-$(clang_version) main"
          sudo apt-get install clang$(clang_version) cmake cmake-data
      - script: |
          mkdir build
          cd build
          cmake .. -DCMAKE_CXX_COMPILER=clang$(clang_version) -DMAKE_INCLUDE_TESTS=ON
          make VERBOSE=1
      - upload: build/boost_tmp_test
        artifact: tmp_test_clang$(clang_version)
          
  - stage: test_linux_clang
    displayName: Clang Linux Test
    dependsOn: build_linux_clang
    jobs:
    - job: test
      pool:
        vmImage: 'ubuntu-16.04'
      strategy:
          matrix:
            clang_5.0:
              clang_version: '-5.0'
            clang_6.0:
              clang_version: '-6.0'
            clang_7.0:
              clang_version: '-7.0'
      steps:
      - download: 'current'
        artifact: tmp_test_clang$(clang_version)
      - script: |
          cd $(Pipeline.Workspace)/tmp_test_clang$(clang_version)
          sudo chmod +x ./boost_tmp_test

  - stage: build_macos_clang
    dependsOn: []
    displayName: Clang MacOS Build
    jobs:
    - job: macos_clang
      pool:
        vmImage: macos-10.13
      steps:
      - script: |
          mkdir build
          cd build
          cmake .. -DCMAKE_CXX_COMPILER=clang++ -DMAKE_INCLUDE_TESTS=ON
          make VERBOSE=1
      - upload: build/boost_tmp_test
        artifact: tmp_test_clang_latest

  - stage: test_macos_clang
    displayName: Clang MacOS Test
    dependsOn: build_macos_clang
    jobs:
    - job: test
      pool:
        vmImage: macos-10.13
      steps:
      - download: 'current'
        artifact: tmp_test_clang_latest
      - script: |
          cd $(Pipeline.Workspace)/tmp_test_clang_latest
          sudo chmod +x ./boost_tmp_test

  - stage: build_msvc_2017
    dependsOn: []
    displayName: MSVC2017 Win10 Build
    jobs:
    - job: build
      pool:
        vmImage: vs2017-win2016
      steps:
      - script: |
          mkdir build
          cd build
          cmake .. -DMAKE_INCLUDE_TESTS=ON
          cmake --build . --config Release
          cd Release
      - upload: build/Release
        artifact: tmp_test_msvc2017

  - stage: test_msvc_2017
    displayName: MSVC2017 Win10 Test
    dependsOn: build_msvc_2017
    jobs:
    - job: test
      pool:
        vmImage: vs2017-win2016
      steps:
      - download: 'current'
        artifact: tmp_test_msvc2017
      - script: |
          cd $(Pipeline.Workspace)/tmp_test_msvc2017
          boost_tmp_test
